# Generated by Django 2.0.2 on 2018-02-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180215_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='th',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
