# Generated by Django 2.0.2 on 2018-02-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180215_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='th',
            field=models.IntegerField(null=True),
        ),
    ]
