# Generated by Django 2.0.1 on 2018-02-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180218_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['modify_date']},
        ),
    ]
